FROM rust:1-alpine

RUN apk add --no-cache musl-dev nodejs npm make && \
    rustup component add rustfmt clippy

WORKDIR /app
COPY . .

RUN cd tests/integration && npm ci

CMD ["make", "check", "test", "integration-test"]
